### ISSUE TITLE
keyframe animation not working

### ISSUE THREAD

**Issue by lawrencecchen** [windicss/svelte-windicss-preprocess#36]
`animate-spin` generates this code:
```css
@keyframes svelte-1fil0v3-spin {
    :global(.windi-sdy900) {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg);
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg)
    }
}
```
Which doesn't work. Real tailwind generates this instead:
```css
@keyframes spin {
    to {
      transform: rotate(1turn);
    }
  }
```
Not sure if this is svelte specific, but I reproduced the issue with the rollup example in this repo: https://github.com/lawrencecchen/svelte-windicss-preprocess/tree/main/example/rollup

**Comment by alexanderniebuhr** [comment]
I have tried this, and it is a problem with the mode `compile: true`
Can you confirm that it is working if you set `compile: false`?

I can this output with `compile: false`

```css
@keyframes spin {
  from {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  to {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
```
