### ISSUE TITLE
v3.0.0-beta.1 - Not working with some classes

### ISSUE THREAD

**Issue by lamualfa** [windicss/svelte-windicss-preprocess#55]
## Example

**Windi CSS Config**

```js
module.exports = {
  theme: {
    extend: {
      margin: {
        large: '4rem',
        medium: '2.5rem',
        small: '1rem',
      },
      colors: {
        primary: {
          DEFAULT: '#991B1B',
          50: '#F0AAAA',
          100: '#EC9494',
          200: '#E46969',
          300: '#DD3D3D',
          400: '#C42323',
          500: '#991B1B',
          600: '#6E1313',
          700: '#420C0C',
          800: '#170404',
          900: '#000000',
        },
      },
    },
  },
};

```

**HTML**

```html
<div class="bg-primary h-1.5 mx-auto rounded-lg  w-30 "></div>
```

**Output CSS**

```css
.rounded-lg {
    border-radius: 0.5rem;
}

.mx-auto {
    margin-left: auto;
    margin-right: auto;
}

// I don't know why, but it will be created 2 times if you use `mx-auto` 2 times in difference place
.mx-auto {
    margin-left: auto;
    margin-right: auto;
}

.bg-primary {
    --tw-bg-opacity: 1;
    background-color: rgba(153, 27, 27, var(--tw-bg-opacity));
}
```

`h-1.5` and `w-30` the two are is missing from CSS Output.

## Environment

- Rollup `v2.33.1`
- Svelte `v3.29.4`
- Windi CSS Preprocess `v3.0.0-beta.1`

I use Routify Framework for the routing library. See https://github.com/lamualfa/routify-windi.
