### ISSUE TITLE
ParseError: Identifier `deep` is expected

### ISSUE THREAD

**Issue by OysterD3** [windicss/svelte-windicss-preprocess#63]
```bash
[!] (plugin svelte) ParseError: Identifier `deep` is expected
node_modules/@responsive-ui/loader/src/Loader.svelte
34:   border-width: 2px;
35: }
36: // .responsive-ui-loader__spinner:after {
     ^
37:   //   content: "";
38:   //   width: 5px;
```

The comment in `<style>` is identified as deep selector.

**Comment by alexanderniebuhr** [comment]
can you explain the bug a bit more? What does it mean? Never saw this. Could you provide source and converted output somehow?

**Comment by OysterD3** [comment]
Here is my `preprocess` config:
```js
// ...
preprocess = [
  sveltePreprocess.typescript(),
  sveltePreprocess.scss(),
  windicssPreprocess.preprocess({
    config: tailwindConfig,
    compile: true,
    prefix: "windi-", // set compilation mode style prefix
    globalPreflight: true, // set preflight style is global or scoped
    globalUtility: true, // set utility style is global or scoped
  }),
];
```

The error I mentioned, it was thrown from [csstree](https://github.com/csstree/csstree), which svelte is depending on it.
If I remove windicssPreprocess from the array, it works fine.

```js
// ...
// working example
preprocess = [
  sveltePreprocess.typescript(),
  sveltePreprocess.scss(),
];
```
___
Now I am having another error.
We have packaged our [components](https://github.com/wetix/responsive-ui) as open-source
```bash
[!] (plugin svelte) ParseError: Unterminated string constant
node_modules/@responsive-ui/label/src/Label.svelte
 8: </script>
 9: 
10: <label class="responsive-ui-label {className" for={forName} {form} {style}>
                                                ^
11:   {label}
12: </label>
ParseError: Unterminated string constant
```

Not sure whether this is related to #35

**Comment by alexanderniebuhr** [comment]
yes, i might know the issue here. not sure if beta.9 (ETA later today) will fix it.
Please post any new info and issues here as well

**Comment by alexanderniebuhr** [comment]
https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.9

**Comment by OysterD3** [comment]
The issue for `ParseError: Identifier `deep` is expected` exists, beta.9 doesn't fix.

**Comment by alexanderniebuhr** [comment]
@OysterD3 which component do you have it in?

**Comment by OysterD3** [comment]
> @OysterD3 which component do you have it in?

### Issue 1

[@responsive-ui/loader](https://github.com/wetix/responsive-ui/tree/master/components/loader)
```bash
# 1.1
[!] (plugin svelte) ParseError: Unterminated string constant
node_modules/@responsive-ui/loader/src/Loader.svelte
 7:   <div class="responsive-ui-loader" in:fade out:fade>
 8:     <div
 9:       class="responsive-ui-loader__spinner responsive-ui-loader__spinner--{size"
                                                                                   ^
10:     />
11:   </div>
```

[@responsive-ui/input](https://github.com/wetix/responsive-ui/tree/master/components/input)
```bash
# 1.2
[!] (plugin svelte) ParseError: Unterminated string constant
node_modules/@responsive-ui/input/src/Input.svelte
20: <input
21:   {...$$restProps}
22:   class="responsive-ui-input {className"
                                           ^
23:   class:responsive-ui-input--bordered={bordered}
24:   bind:this={ref}
```

Not sure whether because of this [6b7fdad](https://github.com/windicss/svelte-windicss-preprocess/commit/6b7fdad) doesn't accept other variables name

___

### Issue 2

```bash
[!] (plugin svelte) ParseError: Identifier `deep` is expected
apps/web/src/pages/movie/cinemas/index.svelte
342:   align-items: center;
343: }
344: .cinema-helper .filter // p {
                             ^
345:   //   color: var(--color-light-grey, #b9b9b9);
346:   //   padding-right: 10px;
```

This is how I wrote my `style (lang=scss)`
```scss
.cinema-helper {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 5px 15px;
    // ...

    .filter {
      display: flex;
      justify-content: center;
      align-items: center;
      // p {
      //   color: var(--color-light-grey, #b9b9b9);
      //   padding-right: 10px;
      // }
      
      // ...
    }
  }
```

___

### Issue 3 (Similar to Issue 2)
```bash
[!] (plugin svelte) ParseError: Identifier is expected
apps/web/src/pages/movie/cinemas/index.svelte
305: }
306: .empty-state {
307:   // position: absolute;
         ^
308:   top: 0;
309:   left: 0;
```
```scss
// style.scss
.empty-state {
    // position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
  }
```
